### ISSUE TITLE
Question 1: Where to retrieve Set fields from?

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#1]
The GET request for **\sets** should retrieve all these fields:
```
  {
    "the set's id": {
      "setName": "a string representing the user generated name of the set",
      "id": 123456,
      "setBelongsTo": "either 'user' or 'team' to identify to the client which group the set is in",
      "type": "a string value that confoms to one of the setTypes passed in /config",
      "filter": "a filter string used by the FilterBuilder representing the last filter applied by this user",
      "sort": [
        "a sort array used by the SortControler representing the last sort applied by this user"
      ],
      "groupByFields" : [ "An array of strings representing the Enum values"],
      "inGroup": "string representing the group this set belongs to or null if it's not in a group",
      "history": [
        {
          "action": "an action taken by the user",
          "actor": "The username associated with the action",
          "date": "a Date string in the format: June 17, 2018 21:12:32"
        }
      ],
      "stats": {
        "count": 12345 // the number of items in the set,
        "createdOn": "a Date string in the format: December 24, 2017 00:24:00",
        "createdBy": "A user name",
        "lastViewed": "a Date string in the format: June 17, 2018 21:12:32",
        "lastViewedBy": "A user name"
      }
    }
  }
```

but the POST request for **\sets** does not store many of these fields as you can see here:
```javascript
  {
    "operation": "A string representing the operation to construct the set. Will always be one of: 'join', 'intersect','difference', or 'filter'",
    "setName": "a string representing the user generated name for the set",
    "sets": [ 
      {
        "id": 12345,
        "negate": true,
        "random": 1345 
      }
    ]   
  }
```
So the questions is, where to retrieve this fields from and how they are related to Set document. 
Thanks.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer See my latest update to the documentation for the `POST /sets` API. I added the fields:
- `setBelongsTo` 
 - `type` 
- `userName` 
- `groupByFields`

This covers some of the fields that you see in GET but not POST. The others should be calculated as follows:
- `history` : This is based on user activity. Initially it is empty. You can ignore this for now and assume it is an empty array.
- `stats.count` : After you POST to /sets, you should calculate the size of the set in the backend. To start, we care the most about sets created through a `filter` operation. For these, you will execute the appropriate filter against the appropriate Mongo collection to get a count. For instance, for Entity, a set created by the filter `numEmailsSent>5 AND numEmailsReceived=10` would have a count of `db.Entity.count({numEmailsSent:{$gt:5},numEmailsReceived:10})`

**Comment by leonardoauer** [comment]
@fatsmcgee Hello, about stats.count:

You said that I should calculate the size of the set in the back-end by executing the appropriate filter, and gave as example Entity collection.

My question is: would be this filter executed always on Entity collections?
If not, how do I know the collection to execute the filter?

Thanks.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer this will be based on the "set type". For now, feel free to assume that the only supported "set type" is `entity` (you can through an exception for other cases).

**Comment by leonardoauer** [comment]
About the filter string -

> > numEmailsSent > 5 AND numEmailsReceived = 10

Which are all the possibilities we should handle?
I'm not talking about the fields, but the operators.

```
>=
<=
<... more??
```

Please detail. 
I did not find a method lessThan in the queryHelper.
`QueryHelpers.lessThan()`

**One more question**... the values some times can be strings right?
They won't be always numbers.
Can they be date or another types?
It will make the logic more complex.

**Comment by leonardoauer** [comment]
How will be a filter query with Field Projection? (I mean the json request)
I took it from Quinn Jar Documentation. 
Will we use sort?

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev To answer each of your questions:

1) For now, the operators we should support are <, >, <=, >= ,and =. For now, nothing else. I don't think this will ever be expanded very much. 
2) For now, assume that the only value types are numbers and strings. Numbers support each operator, and strings only support equality. 
3) Ah you're right, I see that `QueryHelpers` has greater than, but not less than. Feel free to create your own class `QueryHelpers2` which has these static helper:

```java
public class QueryHelpers2 {
    public static ImmutableMap<String, Serializable> lessThan(final int threshold) {
        return ImmutableMap.of(QueryOperator.LT.getValue(), threshold);
    }
    public static ImmutableMap<String, Serializable> lessThanEqualTo(final int threshold) {
        return ImmutableMap.of(QueryOperator.LTE.getValue(), threshold);
    }
    public static ImmutableMap<String, Serializable> lessThan(final double threshold) {
        return ImmutableMap.of(QueryOperator.LT.getValue(), threshold);
    }
    public static ImmutableMap<String, Serializable> lessThanEqualTo(final double threshold) {
        return ImmutableMap.of(QueryOperator.LTE.getValue(), threshold);
    }
}
```

In the above, note that `QueryHelpers` are really pretty dumb... they're basically just maps that end up getting converted to JSON (well,BSON) objects. 

4) For OR, there is a method `QueryConditions.addOrCondition(String field1, Object value1, String field2,Object value2)` which is equivalent to the mongo query:

```javascript
db.Collection.find({$or:[{field1:value1},{field2:value2}]})
```

Two things to note here: 
i) `value1` and `value2` can be maps created by things like `QueryHelpers.greaterThan`
ii) Mongo supports nested `$or`s, so `value1`/`value2` could be something like `{$or:[...]}`

To create a map representing a nested `$or`, I might create a method in `QueryHelpers2` like this:

```java
    public static ImmutableMap<String,Serializable> or(Map<String,Serializable>...clauses){
        return ImmutableMap.of(QueryOperator.OR.getValue(),Lists.newArrayList(clauses));
    }
```

5) The above use of projections is exactly right. The `/entities` API does support sorting, e.g. you could have:

`GET /entities?sort[0]=numEmailsSent.desc&sort[1]=numEmailsReceived.asc`

This would sort the entities first by number of emails sent (in descending order), and then by number of emails received (in ascending order)

For now, assume that you can only pass in one sort field (anything else will give an error, for instance the above example has two sorts so shouldn't be supported).

Suppose you have a simpler sort with one field:

`GET /entities?sort[0]=numEmailsSent.desc`

In the backend you'd specify this by using `QueryConditions.setSortCondition`, e.g.

```java
QueryConditions qc = ...
qc.setSortCondition(new SortCondition(SortType.DESC,"numEmailsSent"))
```

The `POST /sets` and `GET /sets` API, for now, will not care about sorting.

**Comment by fatsmcgee** [comment]
Hey @leonardoauer @stanstempdev

A filter can have more than 3 conditions. The correct behavior is to treat `AND` as having higher precedence than `OR`, similar to how `*` has higher precedence than `+` in arithmetic expressions. For instance, if the filters had parentheses, `a=3 AND b="dog" OR c="cat"` would be equivalent to:

`(a=3 AND b="dog") OR c="cat"`

as another more complex example, `a=3 AND b="dog" AND c="cat" OR d=99 AND e="fish"` would be equivalent to:

`(a=3 AND b="dog" AND c="cat") OR (d=99 AND e="fish")`

This is a bit less complex than most programming languages which have many different operators. Here, you can just split the filter into parts by treating ` OR ` as a separator, then split those parts by their ` AND `operator.  For instance, you can imagine pseudo-code kind of like this:

```python
full_filter = 'a=3 AND b="dog" AND c="cat" OR d=99 AND e="fish"'
and_clauses = full_filter.split(" OR ") 
---> ['a=3 AND b="dog" AND c="cat"', 'd=99 AND e="fish"']
nested_expressions = [clause.split(' AND ') for clause in and_clauses)]
---> [ ['a=3','b="dog"'], ['d=99','e="fish"']]
```

From that, you can make a Mongo query like:
`db.Collection.find({$or:[{a:3,b:"dog"}, {d:99,e:"fish"}]})`

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev 

Good question. There is a hacky way to do this, which I will actually recommend you using for now. Later we will add support for this in core. For now, I'd recommend defining/using a function like this:

```java
    public static void addOrOfAndsToQuery(QueryConditions qc, ArrayList<Map<String,Serializable>> andConditions){
        qc.addSearchCondition(QueryOperator.OR.getValue(),andConditions);
    }
```

For instance, the achieve the above example, you could use:
```java
Map<String,Serializable> andCondition1 = Maps.newHashMap();
Map<String,Serializable> andCondition2 = Maps.newHashMap();
andCondition1.put("a",3);
andCondition1.put("b","dog");
andCondition1.put("c","cat");

andCondition2.put("d",99);
andCondition1.put("e","fish");

ArrayList<Map<String,Serializable>> andConditions = Lists.newArrayList(andCondition1,andCondition2);

QueryConditions qc = new QueryConditions();
addOrOfAndsToQuery(qc,andConditions);
```
