### ISSUE TITLE
How to create Ids on mongo db?

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#10]
@fatsmcgee

I wonder how you create ids in mongo. I went through your project (the core jar) but I didn't find any example. 

I know mongodb automatically creates Ids, but I see in your documents you create ids as string.  

Do you have any utility class?

I also need to understand how to retrieve the just created id, because your save() method does not return the just created object with its respective id. 

Thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev 

I'd recommend using a string ID. In the POJO classes, using the new `Set` collection as an example you'd have something like:

```java
private String setId;
...
public String getSetId(){...}
...
public String setSetId(){...}
```

In the converter classes, you'll set the Mongo document so that `_id` has this ID value.

**Comment by leonardoauer** [comment]
@fatsmcgee

how do you do to retrieve an id of a just created object?, the save() method does not return the id of the new object after being saved. 

One way is to query again,  but i wonder if you have a class in your jar for this purpose that i could use.   

Thanks.

**Comment by leonardoauer** [comment]
@fatsmcgee No need to answer this I have already solved it.
