### ISSUE TITLE
Json response with standard output format

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#12]
HI @fatsmcgee
     I wonder if we can standardized our Json responses. I see we have in the API doc different json responses. 
As an alternative I propose to use this json response format as:

```

> Success example

{
    "code": 2001, // Success message. 4001 code for errors
    "message": // useful text explaining success or error
    "data": {
        "id": 12345,
        "type": "entity",
    }
}

> Error example

{
    "code": 4001, // Error code
    "message": // useful text explaining  the error
}
```

This way I can use a same java class for all api responses. 
Thanks.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer Absolutely. Feel free to edit the API to conform to this.
