### ISSUE TITLE
/sets/groupby endpoint

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#14]
Hi @fatsmcgee

I don't understand what this endpoint should do. 

- **first**
> This endpoint is distinct from the /sets endpoint because it should return an array of sets instead of just a single set.

It says that it should return an array of sets, but the **Expected response example** only has 1 set

- **second**
What should I do in the back-end once I receive this request?

1. Should I save the request body values in the set? 
2. It seems that I should group something but it is not clear enough if I have to group set or entities
3. What should I send as response. 

Please detail what I should do once I receive this request. 
Thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev I edited the API a little bit. Allow me to explain how this should work:

Starting with any set, we can create a new group of sets using this API. For a concrete example, suppose you have a set `all_entities` that represents all `Entity` in the dataset.

Suppose there is a field `name` in `Entity` (there isn't, but it will help the illustration). 

If you do the following `POST /sets/groupby`:
```javascript
  {
    "id": "all_entities" // a set id for the set to perform the groupby operation on
    "groupByFields": ["name"],
    "groupName": "Entities Grouped By Name"
  }
```

In the backend, we will take all of the `Entity` from set `all_entities`, and divide them into groups with unique `name` fields. Each of these groups will  become a *new set*. Suppose the only unique names in the dataset are `"stan"` and `"ethan"`. Then this operation will create two new sets, whose set-related fields will look like this:

```javascript
[
  {
    ...
    "groupByFields":["name"],
    "groupByKeys":["stan"],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["name"],
    "groupByKeys":["ethan"],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
]
```

The above `POST` will return these new sets. 

Notice that `groupByFields` is an array. This allows for nested groupings. Suppose that we want to group Entities by `name`, then by `yearOfBirth` (again, not an actual field, but pretend this exists for illustrative purposes). 

Suppose there is a Stan born in 1920, a Stan born in 2005, and an Ethan born in 1955. Then this `POST /sets/groupby`:
```javascript
  {
    "id": "all_entities" // a set id for the set to perform the groupby operation on
    "groupByFields": ["name","yearOfBirth"],
    "groupName": "Entities Grouped By Name and Year of Birth"
  }
```

Will return something like this:

```javascript
[
  {
    ...
    "groupByFields":["name","yearOfBirth"],
    "groupByKeys":["stan",1920],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["name","yearOfBirth"],
    "groupByKeys":["stan",1920],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["name","yearOfBirth"],
    "groupByKeys":["stan",2005],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["name","yearOfBirth"],
    "groupByKeys":["ethan",1955],
    "inGroup":"Entities Grouped By Name",
    "groupSetParent":"all_entities",
    ...
  },
]
```

**Comment by leonardoauer** [comment]
Hello @fatsmcgee 
I have done most of the logic but I still need a little bit of more information.

 - As show you as example a response for the following request:
   
   Request:
```
  {
    "id": "5C067630A7986C685DCF8E88",
    "groupByFields": "primaryName,numEmailsSent,numEmailsReceived", 
    "groupName": "my first group by"
  }
```
  
  Response:
```
{
    "code": 2001,
    "message": "Group by sets created",
    "data": [
        {
            "id": "5C070B44A7986C214476BB0D",
            "operation": null,
            "name": null,
            "filter": null,
            "belongsTo": null,
            "userName": null,
            "type": null,
            "groupByFields": [
                "primaryName",
                "numEmailsSent",
                "numEmailsReceived"
            ],
            "groupByKeys": [
                "karen d mcilvoy",
                "0",
                "8"
            ],
            "inGroup": "my first group by",
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
        {
            "id": "5C070B44A7986C214476BB0E",
            "operation": null,
            "name": null,
            "filter": null,
            "belongsTo": null,
            "userName": null,
            "type": null,
            "groupByFields": [
                "primaryName",
                "numEmailsSent",
                "numEmailsReceived"
            ],
            "groupByKeys": [
                "rdimichele",
                "0",
                "0"
            ],
            "inGroup": "my first group by",
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
     ... // more data
 	]
 }
```
 
 - Question 1
I have filled in the fields you show me as example, but I do not know how to fill
the remaining fields ( the fields with null values). 
Should I take these values from the parent set? 
Or would you send those values on the body of the JSON request?
 
 - Question 2
 About the groupByField values. 
 Do you have a limited list of the values a user can use for the groupBy?
 As you know, entity for example has a primaryName which is an object. 
 There are many choices here:
 
 a - User can send primaryName as value field, and I could group by primaryName.name, for example. 
 b - Or user can send as values: primaryName.name or primaryName.firstName or primaryName.lastName.   
 
 In Java I could created a big list of all input parameters I could receive (it could be a big list), 
 or a short list if you think there won't be many options for grouping here.
 
 For example what I'm doing now:
 
```
	private String getPersonFieldValue(String groupByField, Person person) {

		String fieldValue = null;
		
		switch (groupByField) {
		case PersonFields.numEmailsSent:
			fieldValue = String.valueOf(person.getNumEmailsSent());
			break;
		case PersonFields.numEmailsReceived:
			fieldValue = String.valueOf(person.getNumEmailsReceived());
			break;
		case PersonFields.primaryName:
			fieldValue = String.valueOf(person.getPrimaryName().getName());
			break;
		case PersonFields.primaryName_FirstName:
			fieldValue = String.valueOf(person.getPrimaryName().getFirstName());
			break;
		default:
			throw new EatException("Invalid groupByFields parameters");
		}
		
		return fieldValue;
	}
  
```
 - Another choice which I prefer but is more expensive is using reflection. 
 It will take me more time to make this feature, but you will be able
 to filter by any field you wish, even new fields that could appear in future. 
 
 Thanks you!

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev Good questions.

*1. Null Fields in /sets/groupby Response*:

* For `userName`/ `belongsTo`/`type`, copy from the parent, as you hinted at. 
* `name` should be called `setName`. I would take this from the `groupName`  passed into `/sets/groupby`. 
* `filter` should be null, initially.
* Populate `operation` as `"groupby"` (a new enum for `operation`).

*2. Allowable Groupby Fields*:

I actually think your approach of doing a manual `switch` is great for now. 

One issue I see with reflection is that the `PersonEntity` java object might not line up 100% with the database schema. 

One thing to keep in mind is that eventually, the UI will give the user a list of choices as to which fields they can group by.  There will probably be some sort of API for getting a list of all valid groupby fields.

**Comment by fatsmcgee** [comment]
And @leonardoauer as a follow up, which `Entity` fields should by allowed for groupby?

I'd say for now, any field (including nested fields) that is a string or a number. Ignore strings that represent dates. That means you shouldn't be able to group by `primaryName`, but you can group by `primaryName.name`. 

I'd also say that you should be able to group by fields in objects contained in sub-arrays. For instance, suppose we the following entities:

```javascript
let e1 = {
...
"emailAddresses" : [
		{
			"emailAddress" : "11-jribnick@interchange-energy.com",
			"emailUserName" : {
				"singleToken" : "11-jribnick",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "interchange-energy.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "P6602497477275973965"
		},
		{
			"emailAddress" : "12-jribnick@interchange-energy.com",
			"emailUserName" : {
				"singleToken" : "12-jribnick",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "interchange-energy.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "N8768493396132688639"
		}
	],
...
}

let e2 = {
...
"emailAddresses" : [
		{
			"emailAddress" : "susan_j_mara@enron.com",
			"emailUserName" : {
				"singleToken" : "susan_j_mara",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "enron.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "P5469596322251641871"
		},
		{
			"emailAddress" : "susan.j.mara@enron.com",
			"emailUserName" : {
				"singleToken" : "susan.j.mara",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "enron.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "P3388172135317792060"
		},
		{
			"emailAddress" : "susan.j.mara2@enron.com",
			"emailUserName" : {
				"singleToken" : "susan.j.mara2",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "enron.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "N7334658600266885817"
		}
	],

...
}

let e3 = {
...
	"emailAddresses" : [
		{
			"emailAddress" : "mtaylo1@enron.com",
			"emailUserName" : {
				"singleToken" : "mtaylo1",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "enron.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "P6438939882942721529"
		},
		{
			"emailAddress" : "mtaylo1@ect.enron.com",
			"emailUserName" : {
				"singleToken" : "mtaylo1",
				"cannotParse" : false
			},
			"domainName" : {
				"domainName" : "ect.enron.com",
				"domainType" : "OTHER"
			},
			"embryoEntityId" : "N6496913191704183468"
		}
	],

...
}
```

For these, if you group by `"emailAddresses.domainName.domainName"`, then entities `e2` and `e3`, but not `e1`, would show up in the `enron.com` group. 

In this setup, groups don't need to be exclusive, e.g. `e3` would also show up in the `ect.enron.com` group.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer 

For the *question a*, perhaps I can offer a simpler hypothetical example to illustrate:

Suppose you are grouping users by their favorite movies, and you allow each user to specify more than one favorite movie. You might have something like this:

```javascript
let stan = {
    name:"Stan",
    favoriteMovies:["The Avengers", "Good Will Hunting"]
};
let ethan = {
    name:"Ethan",
    favoriteMovies:["Good Will Hunting", "The Incredibles"]
};
let leonard = {
    name:"Leonard",
    favoriteMovies:["The Incredibles", "Lawrence of Arabia"]
}
```

Suppose you group by `favoriteMovies`. Then I'd expect four groups, one for each of the distinct movies that were picked (The Avengers, Good Will Hunting, The Incredibles, Lawrence of Arabia).

The group for "The Avengers" would include Stan. The group for "Good Will Hunting" would include Stan and Ethan. The group for "The Incredibles" would include Ethan and Leoard. The group for "Lawrence of Arabia" would only include Leonard.... does that make sense?

In the more complex case, this could also apply for objects nested within groups. For instance, suppose the structure looks like this:

```javascript
let stan = {
    name:"Stan",
    favoriteMovies:[{name:"The Avengers",year:2015}, {name:"Good Will Hunting",year:2001}]
};
```

Then grouping by `favoriteMovies.name` would achieve a similar effect. This is also how you would treat, for instance, `emailAddresses.domainName.domain`. 

For *question b*, see the above. I'd expect that all entities where `stan` appears as *any* name variant would appear in one group, all entities where `ethan` appears as *any* name variant appears in a group, etc....

**Comment by leonardoauer** [comment]
@fatsmcgee 

Could you give me exactly the JSON response you expect for both cases please?
It will really help. It would be more illustrative than words. 
Thank you.

**Comment by leonardoauer** [comment]
By the way, I understood your explanation. But I need to see the response you want.

**Comment by fatsmcgee** [comment]
Sure.

For name variants it would look something like this:

```javascript
{
    "code": 2001,
    "message": "Group by sets created",
    "data": [
        {
            "id": "5C070B44A7986C214476BB0D",
            "operation": "groupby",
            "setName": "my first groupby",
            "filter": null,
            "belongsTo": "user",
            "userName": "Leonard",
            "type": "entity",
            "groupByFields": [
                "nameVariants",
            ],
            "groupByKeys": [
                "enron mark"
            ],
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
        {
            "id": "5C070B44A7986C214476BB0E",
            "operation": "groupby",
            "name": "my first group by",
            "filter": null,
            "belongsTo": null,
            "userName": null,
            "type": null,
            "groupByFields": [
                "primaryName",
                "numEmailsSent",
                "numEmailsReceived"
            ],
            "groupByKeys": [
                "mark enron",
            ],
            "inGroup": "my first group by",
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
     ... // more data
 	]
 }
```

For a more complex nested example (`primaryName.name`, then `emailAddresses.domainName.name`), it might look like this:

```javascript
{
    "code": 2001,
    "message": "Group by sets created",
    "data": [
        {
            "id": "5C070B44A7986C214476BB0D",
            "operation": "groupby",
            "setName": "my first groupby",
            "filter": null,
            "belongsTo": "user",
            "userName": "Leonard",
            "type": "entity",
            "groupByFields": [
               "primaryName.name",
                "emailAddresses.domainName.domainName",
            ],
            "groupByKeys": [
                "jim",
                "enron.com"
            ],
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
       {
            "id": "5C070B44A7986C214476BB0D",
            "operation": "groupby",
            "setName": "my first groupby",
            "filter": null,
            "belongsTo": "user",
            "userName": "Leonard",
            "type": "entity",
            "groupByFields": [
               "primaryName.name",
                "emailAddresses.domainName.domainName",
            ],
            "groupByKeys": [
                "john",
                "enron.com"
            ],
            "groupSetParent": "5C067630A7986C685DCF8E88",
            "stats": null
        },
     ... // more data
 	]
 }
```

**Comment by leonardoauer** [comment]
@fatsmcgee 

I think I have understood now. 
Just to confirm, taking your previous example: 

> ```js
> let e1 = {
> ...
> "emailAddresses" : [
> 		{
> 			"emailAddress" : "11-jribnick@interchange-energy.com",
> 			"emailUserName" : {
> 				"singleToken" : "11-jribnick",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "interchange-energy.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "P6602497477275973965"
> 		},
> 		{
> 			"emailAddress" : "12-jribnick@interchange-energy.com",
> 			"emailUserName" : {
> 				"singleToken" : "12-jribnick",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "interchange-energy.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "N8768493396132688639"
> 		}
> 	],
> ...
> }
> 
> let e2 = {
> ...
> "emailAddresses" : [
> 		{
> 			"emailAddress" : "susan_j_mara@enron.com",
> 			"emailUserName" : {
> 				"singleToken" : "susan_j_mara",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "enron.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "P5469596322251641871"
> 		},
> 		{
> 			"emailAddress" : "susan.j.mara@enron.com",
> 			"emailUserName" : {
> 				"singleToken" : "susan.j.mara",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "enron.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "P3388172135317792060"
> 		},
> 		{
> 			"emailAddress" : "susan.j.mara2@enron.com",
> 			"emailUserName" : {
> 				"singleToken" : "susan.j.mara2",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "enron.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "N7334658600266885817"
> 		}
> 	],
> 
> ...
> }
> 
> let e3 = {
> ...
> 	"emailAddresses" : [
> 		{
> 			"emailAddress" : "mtaylo1@enron.com",
> 			"emailUserName" : {
> 				"singleToken" : "mtaylo1",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "enron.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "P6438939882942721529"
> 		},
> 		{
> 			"emailAddress" : "mtaylo1@ect.enron.com",
> 			"emailUserName" : {
> 				"singleToken" : "mtaylo1",
> 				"cannotParse" : false
> 			},
> 			"domainName" : {
> 				"domainName" : "ect.enron.com",
> 				"domainType" : "OTHER"
> 			},
> 			"embryoEntityId" : "N6496913191704183468"
> 		}
> 	],
> 
> ...
> }
> ```

**The response will be 3 groups:**

```
[
  {
    ...
    "groupByFields":["emailAddresses.domainName.domainName"],
    "groupByKeys":["interchange-energy.com"],
    "inGroup":"Entities Grouped By Domain",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["emailAddresses.domainName.domainName"],
    "groupByKeys":["enron.com"],
    "inGroup":"Entities Grouped By Domain",
    "groupSetParent":"all_entities",
    ...
  },
  {
    ...
    "groupByFields":["emailAddresses.domainName.domainName"],
    "groupByKeys":["ect.enron.com"],
    "inGroup":"Entities Grouped By Domain",
    "groupSetParent":"all_entities",
    ...
  }
]
```
I'll have 3 groups as response, right?

I think your words `would show up` got me a little confused
> then entities `e2` and `e3`, but not `e1`, would show up in the `enron.com` group.
and > `e3` would also show up in the `ect.enron.com` group.
because we are not showing any entity here, just creating sets based on a group by. 

But this `would show up` expression make me guess that at sometime you will execute these sets created by the groupby function. And when you execute any of these sets, entities `would show up` according to the group by field. I don't see any API point now for executing these group by sets.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev 

Perhaps I didn't make this clear enough, but `/sets/groupby` actually creates *new sets*, and effectively returns a `List<EATSet>`. Each of those new sets has `operation=groupby` (it was created through the groupby operation), and has `groupKeys`/`groupValues`. So when the API is run, it will create a new set for each of the possible group keys.  In the backend, you'll store these sets just as any other set.

Does that help?

**Comment by leonardoauer** [comment]
@fatsmcgee 

Yes, that is clear, I'm creating sets.
So the response I wrote above is ok?
Thank you.

**Comment by fatsmcgee** [comment]
Yep, that's right @leonardoauer ! That response looks perfect.
