### ISSUE TITLE
/Documents endpoint

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#17]
@fatsmcgee

Which it the Mongo Collection related to the `/documents` endpoint?

Do we have the related services in the JAR?
I'm not sure if you told me that we are not going to deal with documents yet?

Thank you.

**Comment by fatsmcgee** [comment]
Let's support the `/documents` API. I'll describe exactly how to get each of the fields.

At a high level, there is a one to one mapping between a single `document` and one `EmailChain` in Mongo. An `EmailChain` groups together multiple `Email`s.

From `EmailChain` we use the following fields:

- `externalIdentifier`: This shows up as `docId` in the response.
- `_id`: This shows up as `id` in the response.
- `emailsIds`: These are the IDs which will help us populate the `emails` array, which I describe shortly.

Each item in `emails` corresponds to an item in the Mongo collection `Email`. Within `Email`:

  - The fields `fromId`/`toListIds`/`ccListIds`/`bccListIds` are IDs in the `EmbryoEntity` collection. You will use these to get info for the arrays `to`/`from`/`cc`/`bcc`. In particular:
    * `uid` comes from `EmbryoEntity.uid`
    * Use `EmbryoEntity._id` to find the item in the `Entity` collection which has `EmbryoEntity._id` in its `embryoEntitiesIds` field.
    * Once this `Entity` is found, use `Entity.primaryName.name` for the `primaryName` field.
    * Additionally, use `Entity._id` for the `id` field.

  - The field `content` comes from Elasticsearch, and is accessed by using `DocumentContentService`.
    * Use `DocumentContent documentContent = DocumentContentService.findById(Email._id)`
    * Then populate `content` from `documentContent.getUsableText()`

Much like for the `/entities` end-point, the boolean flag fields (`flagged`/`banned`/`read`) do not currently exist. You should either store these directly in `EmailChain` or create a new collection to store these in.

**Comment by leonardoauer** [comment]
@fatsmcgee 

 - I guess that endpoint `/documents/:id/ban` will update `isPriv` field on Annotation document.
 - `/documents/:id/notes` is same as we did for entities, right?
 - My Annotation document is empty, has no data. How can I populate some data? Or should I do it manually?

Thanks.

**Comment by leonardoauer** [comment]
@fatsmcgee 

Cool, thank you.
