### ISSUE TITLE
Question 3: Id is missing on PUT request for \sets

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#3]
The PUT request for **\sets** describes a body request as:
```
  {
    "setName": "some string representing a new name"
  }
```
but there is no set id. We should have the id field to know which set to update. 
Thanks.

**Comment by leonardoauer** [comment]
@fatsmcgee can we update the API? thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev done.
