### ISSUE TITLE
Question 4: user id missing for GET request for \sets

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#4]
The GET request for **\sets** describes:

> On load the App component makes a requests to get the list of sets available to the user.

but the user Id is missing, what will cause to retrieve all sets from the application. 
We should change this endpoint to **\sets\userId**
Am I right?

Thanks.

**Comment by fatsmcgee** [comment]
@stanstempdev, good question. Instead of doing that, let's make the user ID a query parameter, so something like:

`/sets?userId=leonardoauer`

**Comment by leonardoauer** [comment]
@fatsmcgee can we update the api document? thanks

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev Done.
