### ISSUE TITLE
Question 6: Where should I fetch data of GET request for \entities ?

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#6]
Which is the document I have to retrieve the data for the GET request of **\entities**?
Is all these data in 1 document or several documents?
Thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev please see the updated documentation for this API. To sum up, while answering your question, assume we have a document from`Entity` that we call `e`:

- This should come from all documents from the `Entity` collection, though some fields will require looking at documents from other collections.
- `embryos` will come by finding matching `EmbryoEntity` documents with the equivalent of `db.EmbryoEntity.find({_id:{$in:e.embryoEntitiesIds}})`
-  `emails`  comes from the equivalent of this JS snippet: `e.emailAddresses.map(ea => ea.emailAddress)`
- `notes` comes from a *new* collection that you will create called `EntityNote`, which will have the field `entityId` to allow for lookups. 
- `flagged`/`banned`/`read` will all come from a *new* collection you will create called `EntityFlag`, which whose `_id` will be the same as `e._id`. 
- Ignore `documents` for now. 
- The remaining fields come from `e` itself and are described in the documentation.

**Comment by leonardoauer** [comment]
@fatsmcgee Why do not create `notes, flagged, banned and read` fields on document Entity? instead of creating new documents?

Thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev That would be perfectly valid as well. You can choose to do that instead of creating a new collection. Up to you, and feel free to update the documentation based on the choice you make. To do this on the backend, I might recommend subclassing `PersonEntity` as something like `EATPersonEntity`.

**Comment by leonardoauer** [comment]
Hello @fatsmcgee 

About the json response.
This section -> 
```
      "embryos": {
        "some embryo id":{
          // this follos the EmbryoEntity schema. The client application has a helper method to render 
          // the current list of elements in this object that are listed in the /config response
          // but will render any values that are in this object except for another object
        },
```
Should this section contain the 41 fields of EmbryoEntity document?
See that an entity containing 3 related embryoEntity will contain 41*3 fields.

Thanks.

**Comment by leonardoauer** [comment]
@fatsmcgee 
So an entity could have several notes, right?

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev That is correct, yes.

**Comment by leonardoauer** [comment]
@fatsmcgee 

Which query parameters are mandatory?
We have limit, offset, sort, fields and filter. 
Which of them are mandatory fields?

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev good question.

I'd say that `limit` and `offset` are mandatory, but the others aren't. For the ones that aren't specified:

- null `sort` --> just use any arbitrary sort order (like the default mongo sort order).
- null `fields` --> return all fields.
- null `filter` --> use "match all" logic, like `db.Entity.find({})`

**Comment by leonardoauer** [comment]
Do we have an utility class for handling limit and offset in the queries?

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev Not yet.

For now, do this manually (e.g. run the query yourself, and skip/limit yourself in code).

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev 

For now, include everything except the following fields which can be really huge:
- `toListIds`
- `ccListIds`
- `fromEmailIds`
- `bccEmailIds`
