### ISSUE TITLE
Question 8: Where is the flagged state of an entity?

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#8]
**/entities/:id/flag** 
This endpoint is called by the SetViewer to set or remove the flagged state of a specific entity.

- Where is the flagged state of an entity? which document?
- What does it mean to set a flagged state? Set to value 1?
- What does it mean to remove a flagged state? Set to value 0?
- The DELETE method is supposed to remove the state?

Thanks.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer 

Your last 3 bullet points are correct. To begin, if the user has not done anything, the "flagged state" for a given entity is false by default. 

As for which document in the DB you should update, you have two choices, both of which are perfectly acceptable: 

1) Create a new collection `EntityFlag` that has fields `entityId` and `flag` (a boolean).
2) Add a new field `flag` to the `Entity` collection (which is the `PersonEntity` java object). In the backend, create a subclass of `PersonEntity` that has this field, perhaps `FlaggedPersonEntity`. Then create a converter/IOConfiguration to deal with this field.
